name: Hello World
on: 
  push:
    branches:
     -main
     -develop
     -released/**'
  pull _requests:
     branches:
      -main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Build Step
      run: echo "A demo buld"
