name: Deploy Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.IAM_ACCESSKEY_ID }}
          aws-secret-access-key: ${{ secrets.IAM_SECRET_ACCESSKEY }}
          aws-region: us-east-1

      - name: Upload Website to S3
        run: |
          aws s3 sync Github/STATIC/STATIC s3://teja-first-static-demo-b --delete
