name: Inputs Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

      artifact_tag:
        description: Choose the git tag to deploy
        required: true

jobs:
  inputs-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Artifact Tag: ${{ github.event.inputs.artifact_tag }}"
